2025-06-22 02:11:55,189 - __main__ - INFO - 파일 전송 서버가 ('127.0.0.1', 8888)에서 시작되었습니다.
2025-06-22 02:12:15,617 - __main__ - INFO - 서버에 연결되었습니다: localhost:8888
2025-06-22 02:12:15,618 - __main__ - INFO - 클라이언트 연결: ('::1', 62121, 0, 0)
2025-06-22 02:12:15,618 - __main__ - ERROR - 업로드 실패: 업로드 오류: [Errno 2] No such file or directory: ''
2025-06-22 02:13:12,656 - __main__ - INFO - 서버 연결을 종료했습니다.
2025-06-22 02:13:12,656 - __main__ - ERROR - 메시지 수신 오류: 244 bytes read on a total of 682962941 expected bytes
2025-06-22 02:13:12,656 - __main__ - INFO - 클라이언트 연결 종료: ('::1', 62121, 0, 0)
